# Generated by Django 3.0.6 on 2020-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200514_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='boast_or_roast',
            field=models.BooleanField(default=False, help_text='Boast if clicked'),
        ),
    ]
