# Generated by Django 3.0.6 on 2020-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postitem_boast_or_roast'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postitem',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
